apiVersion: v1
kind: Service
metadata:
    name: server
    labels:
        app: server
spec:
    ports:
    - port: 8000
      targetPort: 8000
    selector:
        app: server
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
    name: server
spec:
    serviceName: pyiyi
    replicas: 2
    template:
        metadata:
            labels:
                app: server
        spec:
            terminationGracePeriodSeconds: 10
            containers:
            - name: python
              image: python:2.7-alpine
              command: ["python"]
              args: ["-mSimpleHTTPServer"]
              workingDir: /web/data
              ports:
                  - containerPort: 8000
              volumeMounts:
                  - mountPath: /web/data
                    name: mypd
    volumeClaimTemplates:
      - metadata:
            name: mypd
        spec:
            accessModes: [ ReadWriteOnce ]
            storageClassName: standard
            resources:
                requests:
                    storage: 100Mi
