apiVersion: v1
kind: PersistentVolume
metadata:
    name: web-data
spec:
    storageClassName: manual
    capacity:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce
    hostPath:
        path: /tmp/data
